version: '3.4'
services:
  api:
    build:
      context: .
      target: api
    environment:
      - DATABASE_URL=postgres://twitterclone:twitterclone@db:5432/dev_twitter_clone
    ports:
      - '4100:4100'
    depends_on:
      - db
    volumes:
      - .:/app/
      - /app/node_modules
    networks:
      - app-network

  db:
    image: postgres:11.1-alpine
    environment:
      - POSTGRES_USER=twitterclone
      - POSTGRES_PASSWORD=twitterclone
      - POSTGRES_DB=dev_twitter_clone
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
